image: docker:latest

services:
  - docker:dind

stages:
  - build
  # - test
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build-docker:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker images
  only:
    - main

# test-docker:
#   stage: test
#   needs:
#     - build-docker
#   script:
#     - docker run --rm $IMAGE_TAG go test ./...
#   only:
#     - main

push-docker:
  stage: push
  needs:
    - build-docker
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_SHA
    - echo $IMAGE_TAG
    - docker images
    - docker push $IMAGE_TAG
  only:
    - main
