---
- import_playbook: master.yml

- name: Wait for master to be ready
  hosts: master
  tasks:
    - name: Ensure k3s is installed
      shell: "sudo k3s kubectl get nodes"
      register: master_check
      until: master_check.stdout | regex_search('Ready')
      retries: 5
      delay: 10

- import_playbook: worker.yml
