---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mail@domain.tld 
    privateKeySecretRef:
      name: le-staging
    solvers:
      - http01:
          ingress:
            class: nginx
