---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storm-config
  namespace: storm
data:
  GRPC_SERVER_ADDR: ":50051"
  KAFKA_BROKER_LIST: "127.0.0.1:9094"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm
  namespace: storm
  labels:
    app.kubernetes.io/name: storm
    app.kubernetes.io/part-of: storm
    app.kubernetes.io/env: prod
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  minReadySeconds: 5
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storm
      app.kubernetes.io/part-of: storm
      app.kubernetes.io/env: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storm
        app.kubernetes.io/part-of: storm
        app.kubernetes.io/env: prod
    spec:
      containers:
        - name: storm
          image: storm:latest
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2"
          envFrom:
            - configMapRef:
                name: storm-config
          securityContext:
            runAsUser: 1000
            fsGroup: 2000
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: storm-service
  namespace: storm
spec:
  selector:
    app.kubernetes.io/name: storm
    app.kubernetes.io/part-of: storm
    app.kubernetes.io/env: prod
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 50051
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: "le-prod"
  name: storm-ingress
  namespace: storm
spec:
  ingressClassName: nginx
  rules:
  - host: "storm.domain.tld"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storm-service
            port:
              number: 8088
  tls:
    - secretName: storm-tls 
      hosts:
        - "storm.domain.tld"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storm-hpa
  namespace: storm
spec:
  minReplicas: 3
  maxReplicas: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storm
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
# ---
# apiVersion: "autoscaling.k8s.io/v1"
# kind: VerticalPodAutoscaler
# metadata:
#   name: storm-vpa
#   namespace: storm
# spec:
#   targetRef:
#     apiVersion: "apps/v1"
#     kind: Deployment
#     name: storm
#   updatePolicy:
#     updateMode: Auto
#   resourcePolicy:
#     containerPolicies:
#       - containerName: '*'
#         minAllowed:
#           cpu: 100m
#           memory: 50Mi
#         maxAllowed:
#           cpu: 1
#           memory: 1G
#         controlledResources: ["cpu", "memory"]
#         controlledValues: RequestsAndLimits
